// Optional DOM regression test: requires Playwright and Chromium. This does not start a live Foundry server.
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const url=req.url.split('?')[0].replace('/modules/n5eb-classmod-library/','/');const f=path.join(root,url);try{res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.svg')?'image/svg+xml':f.endsWith('.png')?'image/png':'application/json');res.end(fs.readFileSync(f));}catch{res.statusCode=404;res.end('missing');}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,headless:true,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1250,height:950}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/module.json`);
await page.evaluate(async()=>{
 document.body.innerHTML='';const base=document.createElement('style');base.textContent='*{box-sizing:border-box}body{margin:0;background:#10131a;color:#edece8;font:14px Arial}button,select,input{font:inherit;color:inherit;background:#212632;border:1px solid #5c6470;border-radius:4px;padding:6px}button{cursor:pointer}button:disabled{opacity:.4}p{line-height:1.5}.application{position:absolute;left:28px;top:24px;display:flex;flex-direction:column;border:1px solid #667080;background:#191e27;border-radius:8px;overflow:hidden}.window-header{padding:12px;background:#252d3b;flex:0 0 42px}.window-content{flex:1;min-height:0;overflow-y:auto}nav{display:flex;flex-direction:row}';document.head.append(base);
 const css=document.createElement('link');css.rel='stylesheet';css.href='/styles/main.css';document.head.append(css);await new Promise(r=>css.onload=r);
 const hooks={};window.Hooks={once:(n,f)=>(hooks[n]??=[]).push(f),on:(n,f)=>(hooks[n]??=[]).push(f)};window.testHooks=hooks;Math.clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
 const clone=v=>structuredClone(v),set=(o,k,v)=>{const ks=k.split('.'),last=ks.pop();for(const key of ks)o=o[key]??={};o[last]=clone(v);};
 class App extends EventTarget{
 constructor(options){super();this.options=options;this.rendered=false;}
 async render(){this.element=document.createElement('div');this.element.className='application '+this.options.classes.join(' ');this.element.style.width=this.options.position.width+'px';this.element.style.height=this.options.position.height+'px';this.element.innerHTML=`<header class="window-header">${this.options.window.title}</header><div class="window-content"></div>`;document.body.append(this.element);this._replaceHTML(await this._renderHTML(),this.element.querySelector('.window-content'),{});this._onRender({},{});this.rendered=true;return this;}
 _onRender(){} bringToFront(){} async close(){this.element.remove();this.rendered=false;this.dispatchEvent(new Event('close'));}
 }
 window.foundry={utils:{escapeHTML:v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),deepClone:clone,mergeObject:(a,b)=>({...a,...b}),randomID:()=>Math.random().toString(36).slice(2),getProperty:(o,k)=>k.split('.').reduce((v,k)=>v?.[k],o),setProperty:set},applications:{api:{ApplicationV2:App,DialogV2:{wait:async()=>null}}}};
 window.ui={notifications:{warn:console.log,error:e=>window.testErrors.push(e),info:()=>{}}};window.testErrors=[];window.canvas={tokens:{controlled:[]}};window.game={user:{id:'p',isGM:false},users:[],actors:[],combats:[],system:{id:'n5eb'},packs:{get:()=>null},time:{worldTime:42},settings:{get:()=>false},modules:{get:()=>({version:'0.19.5'})}};
 window.CONST={ACTIVE_EFFECT_MODES:{ADD:2,OVERRIDE:5,UPGRADE:4}};
 function actor(id,cm){const a={uuid:'Actor.'+id,name:id,documentName:'Actor',type:'character',isOwner:true,items:[],effects:[],apps:{},system:{details:{level:7},abilities:{int:{mod:5}},attributes:{prof:4,hp:{value:110,max:110},chakra:{value:132,max:146}}},flags:{},getFlag:(ns,k)=>a.flags[ns]?.[k],update:async(patch,options={})=>{if(options.parent?.documentName==='Actor')throw new Error('Actor is not a valid embedded Document within the Actor Document');options.parent??=a.parent??null;for(const [key,value]of Object.entries(patch))set(a,key,value);return a;},createEmbeddedDocuments:async(type,data,options={})=>{options.parent??=a;const collection=type==='ActiveEffect'?a.effects:a.items;const docs=data.map((d,i)=>({...clone(d),id:'created'+collection.length+i,getFlag(ns,key){return this.flags?.[ns]?.[key];},async update(patch){for(const [k,v]of Object.entries(patch))set(this,k,v);},async delete(){collection.splice(collection.indexOf(this),1);},toObject(){return clone(d);}}));collection.push(...docs);return docs;},deleteEmbeddedDocuments:async(type,ids)=>{const list=type==='ActiveEffect'?a.effects:a.items;for(let i=list.length-1;i>=0;i--)if(ids.includes(list[i].id))list.splice(i,1);}};a.items=[{type:'classmod',system:{identifier:cm,levels:1},getFlag:()=>null,update:async(patch,options={})=>{options.parent??=a;for(const [k,v]of Object.entries(patch))set(a.items[0],k,v);}}];a.items.get=id=>a.items.find(i=>i.id===id);a.effects.get=id=>a.effects.find(i=>i.id===id);return a;}window.makeActor=actor;window.testSet=set;
 await import('/scripts/rasengan.js');await import('/scripts/main.js');await import('/scripts/madara-cells.js');for(const fn of hooks.ready)await fn();window.previewActor=actor('Itsuki Amagiri','rasengan');window.rasenganWindow=await N5eBRasengan.openTracker(previewActor);
 window.kamaActor=actor('Itsuki Amagiri','kama-seal');kamaActor.flags['n5eb-classmod-library']={kamaTracker:{version:2,divineRewrite:30}};
 const eye={id:'eye',uuid:kamaActor.uuid+'.Item.eye',name:'Latent Sharingan I',getFlag:(ns,k)=>k==='karmicDojutsuFreeActivation',effects:[{id:'effect',transfer:true,disabled:true,flags:{}}],system:{consume:{type:'',amount:0,target:null},activities:[]},toObject(){return {system:clone(this.system)};},async updateEmbeddedDocuments(type,updates){for(const update of updates)Object.assign(this.effects.find(e=>e.id===update._id),update);}};kamaActor.items.push(eye);
});
let boxes=await page.evaluate(()=>{const a=document.querySelector('.n5eb-tracker-sidebar').getBoundingClientRect(),b=document.querySelector('.n5eb-tracker-body').getBoundingClientRect();return {sideRight:a.right,mainLeft:b.left,sideTop:a.top,mainTop:b.top,mainHeight:b.height};});assert.equal(boxes.sideRight,boxes.mainLeft);assert.equal(boxes.sideTop,boxes.mainTop);assert.ok(boxes.mainHeight>600);await page.screenshot({path:path.join(require('os').tmpdir(),'rasengan-0192-overview.png')});
await page.click('[data-tab-button="arts"]');await page.click('[data-action="buy"][data-id="rasengan"]');await page.waitForFunction(()=>N5eBRasengan.getTracker(previewActor).learned.includes('rasengan'));assert.equal(await page.evaluate(()=>previewActor.items.filter(i=>i.flags?.['n5eb-classmod-library']?.rasenganArt==='rasengan').length),1);assert.equal(await page.evaluate(()=>N5eBRasengan.getTracker(previewActor).learned.length),1);assert.equal(await page.locator('[data-rasengan-root]').getAttribute('data-tab'),'arts');assert.equal(await page.locator('.application').count(),1);assert.ok(await page.locator('[data-action="use"][data-id="rasengan"]').isVisible());await page.screenshot({path:path.join(require('os').tmpdir(),'rasengan-0192-arts.png')});
const scroller=await page.locator('.n5eb-tracker-body').evaluate(el=>({height:el.clientHeight,total:el.scrollHeight}));assert.ok(scroller.total>scroller.height);await page.locator('.n5eb-tracker-body').evaluate(el=>el.scrollTop=el.scrollHeight);assert.ok(await page.locator('.rasengan-art').last().isVisible());
// Existing 0.19.1 learned entry with its native item missing is repaired exactly once.
await page.evaluate(async()=>{await rasenganWindow.close();previewActor.items=previewActor.items.filter(i=>!i.flags?.['n5eb-classmod-library']?.rasenganArt);rasenganWindow=await N5eBRasengan.openTracker(previewActor);});assert.equal(await page.evaluate(()=>previewActor.items.filter(i=>i.flags?.['n5eb-classmod-library']?.rasenganArt==='rasengan').length),1);assert.equal(await page.evaluate(()=>N5eBRasengan.getTracker(previewActor).learned.length),1);
await page.evaluate(async()=>{await rasenganWindow.close();window.kamaWindow=await N5eBClassMods.openKamaTracker(kamaActor);});await page.screenshot({path:path.join(require('os').tmpdir(),'kama-0192-overview.png')});await page.click('[data-tab-button="dojutsu"]');await page.click('[data-item-id="eye"]');await page.waitForFunction(()=>!kamaActor.items.find(i=>i.id==='eye').effects[0].disabled);assert.equal(await page.locator('[data-kama-tracker-root]').getAttribute('data-tab'),'dojutsu');assert.equal(await page.locator('[data-item-id="eye"]').textContent(),'Deactivate');await page.click('[data-item-id="eye"]');await page.waitForFunction(()=>kamaActor.items.find(i=>i.id==='eye').effects[0].disabled);await page.screenshot({path:path.join(require('os').tmpdir(),'kama-0192-dojutsu.png')});
await page.evaluate(()=>{kamaWindow.element.style.height='430px';});await page.click('[data-tab-button="overview"]');const km=await page.locator('.n5eb-tracker-body').evaluate(el=>({height:el.clientHeight,total:el.scrollHeight}));assert.ok(km.height>200&&km.total>km.height);await page.locator('.n5eb-tracker-body').evaluate(el=>el.scrollTop=el.scrollHeight);await page.click('[data-action="long-rest"]');assert.equal(await page.locator('.application').count(),1);assert.equal(await page.locator('[data-kama-tracker-root]').getAttribute('data-tab'),'overview');assert.deepEqual(errors,[]);assert.deepEqual(await page.evaluate(()=>testErrors),[]);
// Rasengan partner selection contains PCs only, stores the selected document UUID.
await page.evaluate(async()=>{
 window.ChatMessage={getSpeaker:({actor})=>({actor:actor.uuid}),create:async d=>d};await kamaWindow.close();previewActor.items[0].system.levels=4;window.partnerActor=makeActor('Chidori Player','none');const npc=makeActor('Enemy','none');npc.type='npc';game.actors=[previewActor,partnerActor,npc];
 const catalog=await import('/scripts/rasengan-catalog.js');const art=catalog.ARTS.find(a=>a.partner);
 await previewActor.update({'flags.n5eb-classmod-library.rasenganTracker':{...N5eBRasengan.getTracker(previewActor),learned:[art.id],cores:[]}});
 const previous=foundry.applications.api.DialogV2.wait;foundry.applications.api.DialogV2.wait=async options=>{window.partnerForm=options.content;return {partner:partnerActor.uuid,type:'chakra'};};
 await N5eBRasengan.formArt(previewActor,art.id);foundry.applications.api.DialogV2.wait=previous;game.actors=[];
});
assert.ok(await page.evaluate(()=>partnerForm.includes('<select name="partner"')&&!partnerForm.includes('<input name="partner"')&&!partnerForm.includes('Enemy')));
assert.equal(await page.evaluate(()=>N5eBRasengan.getTracker(previewActor).cores[0].partnerUuid),await page.evaluate(()=>partnerActor.uuid));
// Madara sidebar, scrolling, ownership-scoped menus, actual Sharingan and native cast button.
await page.evaluate(async()=>{
 window.ChatMessage={getSpeaker:({actor})=>({actor:actor.uuid}),create:async d=>d};window.madaraActor=makeActor('Madara Host','madara-cells');madaraActor.items[0].system.levels=2;
 const eye={id:'sharingan',name:'Sharingan',type:'feat',system:{identifier:'sharingan',uses:{max:5,spent:0}},effects:[],getFlag:()=>null,update:async patch=>{for(const [k,v]of Object.entries(patch))testSet(eye,k,v);}};madaraActor.items.push(eye);
 for(let n=0;n<11;n++){
  const identifier='uchiha-technique-'+n,feature={id:'master'+n,name:'Mastered Technique '+n,type:'feat',system:{identifier:'mastered-'+identifier,description:{value:'<p>Mastered benefits for this technique.</p>'}},getFlag:(ns,k)=>({madaraMasteredTechnique:true,baseJutsuIdentifier:identifier})[k]};
  const data={_id:'native'+n,name:'Uchiha Technique '+n,type:'spell',system:{identifier,rank:'c',jutsu:{keywords:['hijutsu']},chakra:{cost:'9'},description:{value:''},activities:{cast:{type:'utility'}}},effects:[]};
  const base={id:data._id,...data,getFlag:()=>null,toObject:()=>structuredClone(data),clone(data){const item={...data,id:base.id,toObject:()=>structuredClone(data)};item.system.activities=[{id:'cast',type:'utility',item,async use(config,dialog,message){for(const hook of testHooks['dnd5e.preActivityConsumption']??[])if(hook(this,config,message)===false)return;const updates={actor:{}};for(const hook of testHooks['dnd5e.activityConsumption']??[])if(hook(this,config,message,updates)===false)return;await madaraActor.update(updates.actor);for(const hook of testHooks['dnd5e.postActivityConsumption']??[])hook(this,config,message);window.madaraNativeCast=config;return {};}}];return item;}};
  madaraActor.items.push(feature,base);
 }
 window.madaraWindow=await N5eBMadaraCells.openTracker(madaraActor);
 const header=[],unrelated=[];for(const fn of testHooks.getHeaderControlsApplicationV2??[]){fn({document:madaraActor},header);fn({actor:madaraActor},unrelated);}window.menuCheck={header:header.filter(c=>c.action==='n5ebMadaraTracker').length,unrelated:unrelated.filter(c=>c.action==='n5ebMadaraTracker').length};
 const menu=document.createElement('div');menu.innerHTML='<div class="window-content"><select><option>Native option</option></select></div>';for(const fn of testHooks.renderApplicationV2??[])fn({actor:madaraActor,element:menu},menu);window.menuStripCount=menu.querySelectorAll('[data-madara-strip]').length;
});
assert.deepEqual(await page.evaluate(()=>menuCheck),{header:1,unrelated:0});assert.equal(await page.evaluate(()=>menuStripCount),0);
boxes=await page.evaluate(()=>{const a=document.querySelector('.n5eb-tracker-sidebar').getBoundingClientRect(),b=document.querySelector('.n5eb-tracker-body').getBoundingClientRect();return {right:a.right,left:b.left,top:a.top,mainTop:b.top};});assert.equal(boxes.right,boxes.left);assert.equal(boxes.top,boxes.mainTop);
await page.click('[data-tab-button="sharingan"]');await page.click('[data-action="toggle-sharingan"]');await page.waitForFunction(()=>madaraActor.effects.some(e=>e.name==='Sharingan'));assert.equal(await page.evaluate(()=>madaraActor.effects.filter(e=>e.name==='Sharingan').length),1);assert.equal(await page.evaluate(()=>madaraActor.items.get('sharingan').system.uses.spent),1);assert.equal(await page.locator('[data-madara-root]').getAttribute('data-tab'),'sharingan');
await page.screenshot({path:path.join(require('os').tmpdir(),'madara-0194-sharingan.png')});
await page.click('[data-tab-button="techniques"]');const scroll=await page.locator('.n5eb-tracker-body').evaluate(el=>({height:el.clientHeight,total:el.scrollHeight}));assert.ok(scroll.total>scroll.height);await page.locator('.n5eb-tracker-body').evaluate(el=>el.scrollTop=el.scrollHeight);assert.ok(await page.locator('[data-action="cast-mastered"]').last().isVisible());
await page.evaluate(()=>{foundry.applications.api.DialogV2.wait=async()=> 'normal';});await page.locator('[data-action="cast-mastered"]').last().click();await page.waitForFunction(()=>!!window.madaraNativeCast);assert.equal(await page.evaluate(()=>madaraActor.system.attributes.chakra.value),125);assert.equal(await page.evaluate(()=>N5eBMadaraCells.getTracker(madaraActor).legacy),38);assert.equal(await page.locator('[data-madara-root]').getAttribute('data-tab'),'techniques');
await page.screenshot({path:path.join(require('os').tmpdir(),'madara-0194-techniques.png')});
// Ongoing techniques keep their own state across tab refreshes, and removal uses the bound DC.
await page.evaluate(async()=>{
 const base=madaraActor.items.get('native0');base.uuid=madaraActor.uuid+'.Item.native0';
 base.clone=data=>{const item={...data,id:base.id,toObject:()=>structuredClone(data)};item.system.activities=[{id:'MadaraFlowerAtk1',type:'attack',item,messageFlags:{},applicableEffects:[],async _createUsageMessage(message){return {id:'flower-ui-card',...message.data,async update(patch){for(const [k,v]of Object.entries(patch))testSet(this,k,v);}};},async rollAttack(){return [{total:20,isCritical:false}];}}];return item;};
 const castItem={...base,getFlag:(ns,k)=>k==='madaraCast'?{mastered:true,identifier:'uchiha-flame-flower',castId:'flower-ui',attack:10,dc:18}:null};
 const data={name:'Flame Flower concentration',flags:{},duration:{seconds:60},changes:[]};for(const fn of testHooks['dnd5e.preBeginConcentrating'])fn(madaraActor,castItem,data);
 window.flowerControl=(await madaraActor.createEmbeddedDocuments('ActiveEffect',[data]))[0];game.combat={id:'ui-fight',round:1,turn:0,combatant:{actor:madaraActor}};
 window.pinnedActor=makeActor('Pinned Target','none');pinnedActor.rollSavingThrow=async config=>{window.removalConfig=config;return [{total:30}];};
 await pinnedActor.createEmbeddedDocuments('ActiveEffect',[{name:'Restrained',flags:{'n5eb-classmod-library':{madaraRemoval:{kind:'restrained',dc:18,casterUuid:madaraActor.uuid,castId:'rain-ui'}}}}]);
 game.actors=[madaraActor,pinnedActor];game.user.targets=new Set([{actor:pinnedActor}]);
 await N5eBMadaraCells.setTracker(madaraActor,{}, {effects:false,syncJutsu:false});
});
await page.click('[data-tab-button="ongoing"]');assert.ok(await page.locator('[data-action="flower-free"]').isEnabled());await page.click('[data-action="flower-free"]');await page.waitForFunction(()=>flowerControl.getFlag('n5eb-classmod-library','madaraOngoing').spheres===7);assert.ok(await page.locator('[data-action="flower-free"]').isDisabled());assert.equal(await page.locator('[data-madara-root]').getAttribute('data-tab'),'ongoing');
await page.click('[data-action="remove-condition"]');await page.waitForFunction(()=>pinnedActor.effects.length===0);assert.deepEqual(await page.evaluate(()=>removalConfig),{ability:'str',target:18});assert.equal(await page.locator('[data-madara-root]').getAttribute('data-tab'),'ongoing');
await page.screenshot({path:path.join(require('os').tmpdir(),'madara-0195-ongoing.png')});
assert.deepEqual(errors,[]);assert.deepEqual(await page.evaluate(()=>testErrors),[]);
console.log('PASS: Rasengan/Kāma sidebar, purchase, repair, scrolling and eyes; player-only partner dropdown; Madara sidebar, scoped menus, actual Sharingan effect/uses, technique scrolling and native cast with normal Chakra. ongoing Flower spheres/free-action limit and source-bound removal. Mock ApplicationV2 host; no live Foundry server.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
