// Optional DOM regression test: requires Playwright and Chromium. This does not start a live Foundry server.
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const url=req.url.split('?')[0].replace('/modules/n5eb-classmod-library/','/');const f=path.join(root,url);try{res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.svg')?'image/svg+xml':f.endsWith('.png')?'image/png':'application/json');res.end(fs.readFileSync(f));}catch{res.statusCode=404;res.end('missing');}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,headless:true,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1250,height:950}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/module.json`);
await page.evaluate(async()=>{
 document.body.innerHTML='';const base=document.createElement('style');base.textContent='*{box-sizing:border-box}body{margin:0;background:#10131a;color:#edece8;font:14px Arial}button,select,input{font:inherit;color:inherit;background:#212632;border:1px solid #5c6470;border-radius:4px;padding:6px}button{cursor:pointer}button:disabled{opacity:.4}p{line-height:1.5}.application{position:absolute;left:28px;top:24px;display:flex;flex-direction:column;border:1px solid #667080;background:#191e27;border-radius:8px;overflow:hidden}.window-header{padding:12px;background:#252d3b;flex:0 0 42px}.window-content{flex:1;min-height:0;overflow-y:auto}nav{display:flex;flex-direction:row}';document.head.append(base);
 const css=document.createElement('link');css.rel='stylesheet';css.href='/styles/main.css';document.head.append(css);await new Promise(r=>css.onload=r);
 const hooks={};window.Hooks={once:(n,f)=>(hooks[n]??=[]).push(f),on:(n,f)=>(hooks[n]??=[]).push(f)};window.testHooks=hooks;Math.clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
 const clone=v=>structuredClone(v),set=(o,k,v)=>{const ks=k.split('.'),last=ks.pop();for(const key of ks)o=o[key]??={};o[last]=clone(v);};
 class App extends EventTarget{
 constructor(options){super();this.options=options;this.rendered=false;}
 async render(){this.element=document.createElement('div');this.element.className='application '+this.options.classes.join(' ');this.element.style.width=this.options.position.width+'px';this.element.style.height=this.options.position.height+'px';this.element.innerHTML=`<header class="window-header">${this.options.window.title}</header><div class="window-content"></div>`;document.body.append(this.element);this._replaceHTML(await this._renderHTML(),this.element.querySelector('.window-content'),{});this._onRender({},{});this.rendered=true;return this;}
 _onRender(){} bringToFront(){} async close(){this.element.remove();this.rendered=false;this.dispatchEvent(new Event('close'));}
 }
 window.foundry={utils:{escapeHTML:v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),deepClone:clone,randomID:()=>Math.random().toString(36).slice(2),getProperty:(o,k)=>k.split('.').reduce((v,k)=>v?.[k],o),setProperty:set},applications:{api:{ApplicationV2:App,DialogV2:{wait:async()=>null}}}};
 window.ui={notifications:{warn:console.log,error:e=>window.testErrors.push(e),info:()=>{}}};window.testErrors=[];window.canvas={tokens:{controlled:[]}};window.game={user:{id:'p',isGM:false},users:[],actors:[],combats:[],system:{id:'n5eb'},packs:{get:()=>null},time:{worldTime:42},settings:{get:()=>false},modules:{get:()=>({version:'0.19.2'})}};
 window.CONST={ACTIVE_EFFECT_MODES:{ADD:2,OVERRIDE:5}};
 function actor(id,cm){const a={uuid:'Actor.'+id,name:id,documentName:'Actor',isOwner:true,items:[],effects:[],apps:{},system:{details:{level:7},abilities:{int:{mod:5}},attributes:{hp:{value:110,max:110},chakra:{value:132,max:146}}},flags:{},getFlag:(ns,k)=>a.flags[ns]?.[k],update:async patch=>{for(const [key,value]of Object.entries(patch))set(a,key,value);return a;},createEmbeddedDocuments:async(type,data)=>{const docs=data.map((d,i)=>({...clone(d),id:'created'+a.items.length+i}));a.items.push(...docs);return docs;},deleteEmbeddedDocuments:async(type,ids)=>a.items=a.items.filter(i=>!ids.includes(i.id))};a.items=[{type:'classmod',system:{identifier:cm,levels:1},getFlag:()=>null,update:async patch=>{for(const [k,v]of Object.entries(patch))set(a.items[0],k,v);}}];return a;}
 await import('/scripts/rasengan.js');await import('/scripts/main.js');for(const fn of hooks.ready)await fn();window.previewActor=actor('Itsuki Amagiri','rasengan');window.rasenganWindow=await N5eBRasengan.openTracker(previewActor);
 window.kamaActor=actor('Itsuki Amagiri','kama-seal');kamaActor.flags['n5eb-classmod-library']={kamaTracker:{version:2,divineRewrite:30}};
 const eye={id:'eye',uuid:kamaActor.uuid+'.Item.eye',name:'Latent Sharingan I',getFlag:(ns,k)=>k==='karmicDojutsuFreeActivation',effects:[{id:'effect',transfer:true,disabled:true,flags:{}}],system:{consume:{type:'',amount:0,target:null},activities:[]},toObject(){return {system:clone(this.system)};},async updateEmbeddedDocuments(type,updates){for(const update of updates)Object.assign(this.effects.find(e=>e.id===update._id),update);}};kamaActor.items.push(eye);
});
let boxes=await page.evaluate(()=>{const a=document.querySelector('.n5eb-tracker-sidebar').getBoundingClientRect(),b=document.querySelector('.n5eb-tracker-body').getBoundingClientRect();return {sideRight:a.right,mainLeft:b.left,sideTop:a.top,mainTop:b.top,mainHeight:b.height};});assert.equal(boxes.sideRight,boxes.mainLeft);assert.equal(boxes.sideTop,boxes.mainTop);assert.ok(boxes.mainHeight>600);await page.screenshot({path:path.join(require('os').tmpdir(),'rasengan-0192-overview.png')});
await page.click('[data-tab-button="arts"]');await page.click('[data-action="buy"][data-id="rasengan"]');await page.waitForFunction(()=>N5eBRasengan.getTracker(previewActor).learned.includes('rasengan'));assert.equal(await page.evaluate(()=>previewActor.items.filter(i=>i.flags?.['n5eb-classmod-library']?.rasenganArt==='rasengan').length),1);assert.equal(await page.evaluate(()=>N5eBRasengan.getTracker(previewActor).learned.length),1);assert.equal(await page.locator('[data-rasengan-root]').getAttribute('data-tab'),'arts');assert.equal(await page.locator('.application').count(),1);assert.ok(await page.locator('[data-action="use"][data-id="rasengan"]').isVisible());await page.screenshot({path:path.join(require('os').tmpdir(),'rasengan-0192-arts.png')});
const scroller=await page.locator('.n5eb-tracker-body').evaluate(el=>({height:el.clientHeight,total:el.scrollHeight}));assert.ok(scroller.total>scroller.height);await page.locator('.n5eb-tracker-body').evaluate(el=>el.scrollTop=el.scrollHeight);assert.ok(await page.locator('.rasengan-art').last().isVisible());
// Existing 0.19.1 learned entry with its native item missing is repaired exactly once.
await page.evaluate(async()=>{await rasenganWindow.close();previewActor.items=previewActor.items.filter(i=>!i.flags?.['n5eb-classmod-library']?.rasenganArt);rasenganWindow=await N5eBRasengan.openTracker(previewActor);});assert.equal(await page.evaluate(()=>previewActor.items.filter(i=>i.flags?.['n5eb-classmod-library']?.rasenganArt==='rasengan').length),1);assert.equal(await page.evaluate(()=>N5eBRasengan.getTracker(previewActor).learned.length),1);
await page.evaluate(async()=>{await rasenganWindow.close();window.kamaWindow=await N5eBClassMods.openKamaTracker(kamaActor);});await page.screenshot({path:path.join(require('os').tmpdir(),'kama-0192-overview.png')});await page.click('[data-tab-button="dojutsu"]');await page.click('[data-item-id="eye"]');await page.waitForFunction(()=>!kamaActor.items.find(i=>i.id==='eye').effects[0].disabled);assert.equal(await page.locator('[data-kama-tracker-root]').getAttribute('data-tab'),'dojutsu');assert.equal(await page.locator('[data-item-id="eye"]').textContent(),'Deactivate');await page.click('[data-item-id="eye"]');await page.waitForFunction(()=>kamaActor.items.find(i=>i.id==='eye').effects[0].disabled);await page.screenshot({path:path.join(require('os').tmpdir(),'kama-0192-dojutsu.png')});
await page.evaluate(()=>{kamaWindow.element.style.height='430px';});await page.click('[data-tab-button="overview"]');const km=await page.locator('.n5eb-tracker-body').evaluate(el=>({height:el.clientHeight,total:el.scrollHeight}));assert.ok(km.height>200&&km.total>km.height);await page.locator('.n5eb-tracker-body').evaluate(el=>el.scrollTop=el.scrollHeight);await page.click('[data-action="long-rest"]');assert.equal(await page.locator('.application').count(),1);assert.equal(await page.locator('[data-kama-tracker-root]').getAttribute('data-tab'),'overview');assert.deepEqual(errors,[]);assert.deepEqual(await page.evaluate(()=>testErrors),[]);
console.log('PASS: left sidebar, tabs, click purchase/native item, no accidental close, old-purchase repair, 20-Art scroll, eye activation/deactivation, short-window Kāma scroll/rest. Mock ApplicationV2 host; no live Foundry server.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
