const MODULE_ID = "n5eb-classmod-library";
const CLASSMOD_ID = "hashirama-cells";
const TRACKER_FLAG = "hashiramaCellsTracker";
const EFFECT_FLAG = "hashiramaCellsPassiveEffect";
const HOSTILITY_EFFECT_FLAG = "hashiramaCellsHostilityEffect";
const INTERNAL = MODULE_ID;
const ICON = `modules/${MODULE_ID}/assets/hashirama-cells.png`;
const dialogs = new Map();
const queues = new Map();

function arr(v){ return v ? (Array.isArray(v) ? v : Array.from(v)) : []; }
function esc(v){ return foundry.utils.escapeHTML(String(v ?? "")); }
function actorKey(actor){ return actor?.uuid ?? actor?.id ?? null; }
function queue(actor,task){ const key=actorKey(actor); if(!key) return Promise.resolve().then(task); const prior=queues.get(key)??Promise.resolve(); const current=prior.catch(()=>{}).then(task); queues.set(key,current); return current.finally(()=>{if(queues.get(key)===current)queues.delete(key);}); }
function flag(doc,key){ return doc?.getFlag?.(MODULE_ID,key) ?? doc?.flags?.[MODULE_ID]?.[key]; }
function getClassMod(actor){ return arr(actor?.items).find(i=>i.type==="classmod"&&i.system?.identifier===CLASSMOD_ID)??null; }
function getLevel(actor){ return Math.max(0,Math.min(5,Number(getClassMod(actor)?.system?.levels??0))); }
function has(actor,id){ return arr(actor?.items).some(i=>i.system?.identifier===id); }
function conMod(actor){ const a=actor?.system?.abilities?.con??{}; return Number.isFinite(Number(a.mod))?Number(a.mod):Math.floor((Number(a.value??10)-10)/2); }
function maxLegacy(actor){ return 20*getLevel(actor); }
function clamp(v,min,max){ return Math.min(max,Math.max(min,Number(v)||0)); }
function getActivityItem(activity){ return activity?.item ?? activity?.parent?.item ?? null; }
function currentTurnKey(combat=game.combat){ if(!combat) return ""; return `${combat.id}:${combat.round??0}:${combat.turn??0}`; }
function defaultTracker(actor){ return {version:1,legacy:maxLegacy(actor),hostility:false,hostilityDc:20,lastTurnKey:"",lastHostilityCheck:"",lastRegen:0,mutationSkills:{}}; }
function normalizeTracker(actor,v={}){ return {version:1,legacy:clamp(v.legacy,0,maxLegacy(actor)),hostility:Boolean(v.hostility)&&getLevel(actor)<5,hostilityDc:Math.max(20,Number(v.hostilityDc??20)),lastTurnKey:String(v.lastTurnKey??""),lastHostilityCheck:String(v.lastHostilityCheck??""),lastRegen:Math.max(0,Number(v.lastRegen??0)),mutationSkills:(v.mutationSkills&&typeof v.mutationSkills==="object")?v.mutationSkills:{}}; }
function readTracker(actor){ return normalizeTracker(actor,actor?.getFlag?.(MODULE_ID,TRACKER_FLAG)??defaultTracker(actor)); }
async function writeTracker(actor,patch={}, {render=true,effects=true}={}){ const next=normalizeTracker(actor,{...readTracker(actor),...patch}); const raw=actor?.getFlag?.(MODULE_ID,TRACKER_FLAG); if(!raw||JSON.stringify(raw)!==JSON.stringify(next)) await actor.update({[`flags.${MODULE_ID}.${TRACKER_FLAG}`]:next},{[INTERNAL]:{hashirama:true}}); if(effects) await refreshEffects(actor,next); if(render){ actor.sheet?.render?.(false); refreshDialog(actor); } return next; }

function addChange(changes,key,value,mode=CONST.ACTIVE_EFFECT_MODES.ADD,priority=20){ if(Number(value)) changes.push({key,mode,value:String(value),priority}); }
function passiveChanges(actor){ const level=getLevel(actor), changes=[]; if(!level)return changes; const conBonus=level>=5?6:level>=3?4:2; addChange(changes,"system.abilities.con.value",conBonus); addChange(changes,"system.abilities.con.max",conBonus);
  if(level>=4){ for(const a of ["str","dex","con"]) addChange(changes,`system.abilities.${a}.bonuses.check`,level); }
  const saveBonus=Math.ceil(level/2); if(has(actor,"physical-perfection")) for(const a of ["str","dex","con"]) addChange(changes,`system.abilities.${a}.bonuses.save`,saveBonus);
  if(has(actor,"mental-perfection")) for(const a of ["int","wis","cha"]) addChange(changes,`system.abilities.${a}.bonuses.save`,saveBonus);
  return changes;
}
async function refreshEffects(actor,state=readTracker(actor)){
  let passive=arr(actor?.effects).find(e=>flag(e,EFFECT_FLAG)); const changes=passiveChanges(actor);
  if(!getClassMod(actor)){ if(passive) await passive.delete({[INTERNAL]:{hashirama:true}}); return; }
  const pData={name:"Hashirama Cells — Passive Adaptation",img:ICON,disabled:false,transfer:false,changes,statuses:[],flags:{[MODULE_ID]:{[EFFECT_FLAG]:true}}};
  if(!passive) await actor.createEmbeddedDocuments("ActiveEffect",[pData],{[INTERNAL]:{hashirama:true}}); else if(passive.img!==ICON||JSON.stringify(passive.changes??[])!==JSON.stringify(changes)||passive.disabled) await passive.update(pData,{[INTERNAL]:{hashirama:true}});
  let hostility=arr(actor?.effects).find(e=>flag(e,HOSTILITY_EFFECT_FLAG));
  if(state.hostility&&getLevel(actor)<5){ const hData={name:"Wooden Hostility",img:ICON,disabled:false,transfer:false,changes:[],statuses:[],flags:{[MODULE_ID]:{[HOSTILITY_EFFECT_FLAG]:true}}}; if(!hostility) await actor.createEmbeddedDocuments("ActiveEffect",[hData],{[INTERNAL]:{hashirama:true}}); else if(hostility.disabled||hostility.img!==ICON) await hostility.update(hData,{[INTERNAL]:{hashirama:true}}); }
  else if(hostility) await hostility.delete({[INTERNAL]:{hashirama:true}});
}
async function cleanupActor(actor){ const state=readTracker(actor); const updates={}; for(const [key,data] of Object.entries(state.mutationSkills??{})){ const cur=Number(actor.system?.skills?.[key]?.value??0); if(cur===Number(data.applied)) updates[`system.skills.${key}.value`]=Number(data.original??0); } if(Object.keys(updates).length) await actor.update(updates,{[INTERNAL]:{hashirama:true}}); const effects=arr(actor.effects).filter(e=>flag(e,EFFECT_FLAG)||flag(e,HOSTILITY_EFFECT_FLAG)); if(effects.length) await actor.deleteEmbeddedDocuments("ActiveEffect",effects.map(e=>e.id),{[INTERNAL]:{hashirama:true}}); await actor.unsetFlag(MODULE_ID,TRACKER_FLAG); }
async function ensureActor(actor){ if(!getClassMod(actor)) return; const raw=actor.getFlag?.(MODULE_ID,TRACKER_FLAG); if(!raw) await writeTracker(actor,defaultTracker(actor),{render:false}); else { const state=readTracker(actor); if(getLevel(actor)>=5&&state.hostility) await writeTracker(actor,{hostility:false,hostilityDc:20},{render:false}); else await refreshEffects(actor,state); } await syncDynamicDamage(actor); }

function regenDie(actor){ let die=4; if(has(actor,"improved-regeneration")) die=Math.min(12,die+2); if(has(actor,"true-regeneration")) die=Math.min(12,die+2); return die; }
function regenFormula(actor){ const level=getLevel(actor), count=level>=5?4:level>=3?2:1, die=regenDie(actor), mod=conMod(actor); return `${count}d${die}${mod>=0?'+':''}${mod}`; }
function regenEligible(actor){ const level=getLevel(actor), hp=actor.system?.attributes?.hp??{}, value=Number(hp.value??0), max=Number(hp.max??value); if(!max||value>=max)return false; if(level>=5)return true; return value/max < (level>=3?.75:.5); }
async function roll(actor,formula,label){ const r=await new Roll(formula).evaluate(); await r.toMessage({speaker:ChatMessage.getSpeaker({actor}),flavor:`${actor.name} — ${label}`}); return Number(r.total??0); }
async function heal(actor,amount,label){ const hp=actor.system?.attributes?.hp??{}, cur=Number(hp.value??0), max=Number(hp.max??cur), next=Math.min(max,cur+Math.max(0,amount)); if(next!==cur) await actor.update({"system.attributes.hp.value":next},{[INTERNAL]:{hashirama:true}}); if(amount) ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>${esc(actor.name)} — ${esc(label)}:</strong> healed ${Math.max(0,next-cur)} HP.</p>`}); return Math.max(0,next-cur); }
async function damageSelf(actor,amount,label){ const hp=actor.system?.attributes?.hp??{}, cur=Number(hp.value??0), next=Math.max(0,cur-Math.max(0,amount)); await actor.update({"system.attributes.hp.value":next},{[INTERNAL]:{hashirama:true}}); ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>${esc(actor.name)} — ${esc(label)}:</strong> takes ${Math.max(0,cur-next)} damage.</p>`}); return cur-next; }
async function hostilityCheck(actor,{escape=false}={}){ const state=readTracker(actor), adv=has(actor,"partial-match")&&!escape, dis=escape; const formula=`${adv?'2d20kh':dis?'2d20kl':'1d20'}${conMod(actor)>=0?'+':''}${conMod(actor)}`; const total=await roll(actor,formula,escape?"Wooden Hostility — Control Check":"Hashirama Cells — Hostility Check"); const success=total>=state.hostilityDc; if(success){ await writeTracker(actor,{hostility:escape?false:state.hostility,hostilityDc:escape?20:state.hostilityDc+1,lastHostilityCheck:`${total} vs DC ${state.hostilityDc} — success`},{render:false}); if(escape) ui.notifications.info(`${actor.name} regains control of the Hashirama Cells.`); }
  else { await writeTracker(actor,{hostility:true,lastHostilityCheck:`${total} vs DC ${state.hostilityDc} — failure`},{render:false}); ui.notifications.warn(`${actor.name} enters Wooden Hostility.`); }
  refreshDialog(actor); return success;
}
async function processTurn(actor,combat){ const level=getLevel(actor); if(!level)return; const key=currentTurnKey(combat), state=readTracker(actor); if(!key||state.lastTurnKey===key)return; await writeTracker(actor,{lastTurnKey:key},{render:false,effects:false}); const hp=actor.system?.attributes?.hp??{}, value=Number(hp.value??0), max=Number(hp.max??value);
  if(level>=5){ if(state.hostility) await writeTracker(actor,{hostility:false,hostilityDc:20},{render:false}); if(regenEligible(actor)){ const amount=Math.max(0,await roll(actor,regenFormula(actor),"Passive Regeneration")); const healed=await heal(actor,amount,"Passive Regeneration"); await writeTracker(actor,{lastRegen:healed},{render:false,effects:false}); } return; }
  if(readTracker(actor).hostility){ const dmg=Math.max(0,await roll(actor,"2d4","Wooden Hostility Damage")); await damageSelf(actor,dmg,"Wooden Hostility"); return; }
  if(max>0&&value/max<.5) await hostilityCheck(actor);
  if(!readTracker(actor).hostility&&regenEligible(actor)){ const amount=Math.max(0,await roll(actor,regenFormula(actor),"Passive Regeneration")); const healed=await heal(actor,amount,"Passive Regeneration"); await writeTracker(actor,{lastRegen:healed},{render:false,effects:false}); }
  if(Number(actor.system?.attributes?.hp?.value??0)/Math.max(1,Number(actor.system?.attributes?.hp?.max??1))>=.5 && readTracker(actor).hostilityDc!==20) await writeTracker(actor,{hostilityDc:20},{render:false,effects:false});
}

async function spendLegacy(actor,amount,reason="Legacy Chakra"){ amount=Math.max(0,Math.floor(Number(amount)||0)); if(!amount)return true; const state=readTracker(actor), fromLegacy=Math.min(state.legacy,amount), missing=amount-fromLegacy; let chakraCost=0; if(missing){ if(getLevel(actor)<5){ui.notifications.warn(`Not enough Legacy Chakra (${state.legacy}/${amount}).`);return false;} chakraCost=missing*3; const chakra=Number(actor.system?.attributes?.chakra?.value??0); if(chakra<chakraCost){ui.notifications.warn(`Perfect Match needs ${chakraCost} regular Chakra for the missing ${missing} Legacy Chakra.`);return false;} await actor.update({"system.attributes.chakra.value":chakra-chakraCost},{[INTERNAL]:{hashirama:true}}); }
  await writeTracker(actor,{legacy:state.legacy-fromLegacy},{render:false}); ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>${esc(actor.name)} — ${esc(reason)}:</strong> spent ${amount} Legacy Chakra${chakraCost?` (${chakraCost} regular Chakra converted through Perfect Match)`:''}.</p>`}); refreshDialog(actor); return true; }
async function changeLegacy(actor,delta){ const s=readTracker(actor); await writeTracker(actor,{legacy:s.legacy+Number(delta||0)}); }
async function activatePerfected(actor){ const arts=arr(actor.items).filter(i=>flag(i,"hashiramaPerfectedArt")); if(!arts.length)return ui.notifications.warn("No Perfected Wood Art is owned."); const options=arts.map(i=>`<option value="${esc(i.id)}">${esc(i.name)}</option>`).join(''); const result=await foundry.applications.api.DialogV2.wait({window:{title:"Activate Perfected Wood Art"},content:`<form><div class="form-group"><label for="hc-perfect-art">Perfected Art</label><select id="hc-perfect-art" name="art">${options}</select></div></form>`,buttons:[{action:"activate",label:"Spend 5 Legacy Chakra",default:true,callback:(event,button)=>new FormDataExtended(button.form).object.art},{action:"cancel",label:"Cancel"}],rejectClose:false}); if(!result)return; const item=actor.items.get(result); if(!item)return; if(!await spendLegacy(actor,5,item.name))return; let extra=""; if(item.system.identifier==="perfected-tree-bind-flourish-burial"){ const amount=await roll(actor,`${getLevel(actor)}d8`,`${item.name} — Bonus Earth Damage`); extra=`<p>Bonus Earth damage roll: <strong>${amount}</strong>.</p>`; }
  ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<h3>${esc(item.name)} — Perfected</h3>${item.system?.description?.value??''}${extra}`}); }
async function useSplinters(actor){ if(!has(actor,"overwhelming-splinters"))return ui.notifications.warn("You do not have Overwhelming Splinters."); const cap=getLevel(actor)*10, state=readTracker(actor); const result=await foundry.applications.api.DialogV2.wait({window:{title:"Overwhelming Splinters"},content:`<form><div class="form-group"><label for="hc-splinters">Legacy Chakra to spend (max ${cap})</label><input id="hc-splinters" name="amount" type="number" min="1" max="${cap}" value="${Math.min(cap,Math.max(1,state.legacy))}"></div></form>`,buttons:[{action:"use",label:"Spend & Roll Damage",default:true,callback:(event,button)=>Number(new FormDataExtended(button.form).object.amount)},{action:"cancel",label:"Cancel"}],rejectClose:false}); const amount=Math.min(cap,Math.max(0,Number(result)||0)); if(!amount)return; if(!await spendLegacy(actor,amount,"Overwhelming Splinters"))return; await roll(actor,String(amount),"Overwhelming Splinters — Additional Damage"); }
async function useLegacySuppression(actor){ if(getLevel(actor)<4)return ui.notifications.warn("Legacy Chakra suppression unlocks at Hashirama Cells level 4."); const result=await foundry.applications.api.DialogV2.wait({window:{title:"Legacy Chakra — Chakra Suppression"},content:`<form><div class="form-group"><label for="hc-suppress-rank">Jutsu Rank</label><select id="hc-suppress-rank" name="rank"><option value="1">D-Rank</option><option value="2">C-Rank</option><option value="3">B-Rank</option><option value="4">A-Rank</option><option value="5">S-Rank</option></select></div><div class="form-group"><label for="hc-suppress-target">Target Type</label><select id="hc-suppress-target" name="target"><option value="minion">Minion</option><option value="standard">Standard</option><option value="elite">Elite</option><option value="solo">Solo</option></select></div></form>`,buttons:[{action:"apply",label:"Resolve",default:true,callback:(event,button)=>new FormDataExtended(button.form).object},{action:"cancel",label:"Cancel"}],rejectClose:false}); if(!result||typeof result!=="object")return; const rank=Math.max(1,Math.min(5,Number(result.rank)||1)), target=String(result.target||"standard"); if(target==="minion"){ ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>${esc(actor.name)} — Legacy Chakra:</strong> the Minion cannot cast jutsu or spend Chakra for 1 minute.</p>`}); return; } const mult={standard:10,elite:15,solo:20}[target]??10; await roll(actor,String(mult*rank),`Legacy Chakra — ${target} Chakra Damage`); }

function requiredMutationCount(actor){ return Math.max(0,getLevel(actor)-1); }
async function chooseMutationSkill(actor){ const s=readTracker(actor), chosen=s.mutationSkills??{}, needed=requiredMutationCount(actor); if(Object.keys(chosen).length>=needed)return ui.notifications.info("All Extraordinary Mutation skill choices for the current Class Mod level are already selected."); const skills=actor.system?.skills??{}; const available=Object.entries(skills).filter(([k])=>!chosen[k]); if(!available.length)return ui.notifications.warn("No available skills found on this Actor."); const options=available.map(([k,v])=>`<option value="${esc(k)}">${esc(v?.label??CONFIG?.DND5E?.skills?.[k]?.label??k)} — ${Number(v?.value??0)>=1?'Expertise':'Proficiency'}</option>`).join(''); const result=await foundry.applications.api.DialogV2.wait({window:{title:"Extraordinary Mutation"},content:`<form><div class="form-group"><label for="hc-mutation-skill">Skill (${Object.keys(chosen).length+1}/${needed})</label><select id="hc-mutation-skill" name="skill">${options}</select></div></form>`,buttons:[{action:"save",label:"Apply",default:true,callback:(event,button)=>new FormDataExtended(button.form).object.skill},{action:"cancel",label:"Cancel"}],rejectClose:false}); if(!result||!skills[result])return; const original=Number(skills[result].value??0), applied=original>=1?Math.max(2,original):1; await actor.update({[`system.skills.${result}.value`]:applied},{[INTERNAL]:{hashirama:true}}); await writeTracker(actor,{mutationSkills:{...chosen,[result]:{original,applied}}}); }

async function syncDynamicDamage(actor){ const level=getLevel(actor); if(!level)return; const updates=[]; for(const item of arr(actor.items)){ if(item.system?.identifier!=="perfected-tree-bind-flourish-burial")continue; const expected=[[`${level}d8`,"earth"]]; if(JSON.stringify(item.system?.damage?.parts??[])!==JSON.stringify(expected)) updates.push({_id:item.id,"system.damage.parts":expected}); } if(updates.length) await actor.updateEmbeddedDocuments("Item",updates,{[INTERNAL]:{hashirama:true}}); }
async function applyRest(actor,type){ if(!["long","full"].includes(type))return; let amount=0; const updates={}; if(has(actor,"partial-match")){ amount=Math.max(0,await roll(actor,`2*(${regenFormula(actor)})`,"Partial Match — Rest Temporary HP")); const hp=actor.system?.attributes?.hp??{}, temp=Number(hp.temp??0); updates["system.attributes.hp.temp"]=Math.max(temp,amount); } if(Object.keys(updates).length) await actor.update(updates,{[INTERNAL]:{hashirama:true}}); await writeTracker(actor,{legacy:maxLegacy(actor),hostilityDc:20,lastTurnKey:""},{render:false}); ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>${esc(actor.name)} — Hashirama Cells:</strong> Legacy Chakra restored to ${maxLegacy(actor)}.${has(actor,'partial-match')?` Partial Match grants ${amount} temporary HP.`:''}</p>`}); refreshDialog(actor); }

function trackerHtml(actor){ const s=readTracker(actor), level=getLevel(actor), selected=arr(actor.items).filter(i=>flag(i,"hashiramaPerfectedArt")).length, mut=Object.keys(s.mutationSkills??{}).length, needed=requiredMutationCount(actor); return `<div class="n5eb-hashirama-tracker" data-hashirama-root><header><div><h2>Hashirama Cells</h2><p>Class Mod Level ${level}</p></div><div class="legacy-orb">${s.legacy}<small>/${maxLegacy(actor)}</small></div></header><section class="hashirama-grid"><div><span>Legacy Chakra</span><strong>${s.legacy}/${maxLegacy(actor)}</strong></div><div><span>Regeneration</span><strong>${esc(regenFormula(actor))}</strong></div><div><span>Wooden Hostility</span><strong>${s.hostility?'ACTIVE':`DC ${s.hostilityDc}`}</strong></div><div><span>Perfected Arts</span><strong>${selected}/${level}</strong></div><div><span>Mutation Skills</span><strong>${mut}/${needed}</strong></div><div><span>Wood Armor AC</span><strong>${has(actor,'wood-armor')?15+conMod(actor)+Math.floor(Number(actor.system?.attributes?.prof??0)/2):'—'}</strong></div></section><footer><button type="button" data-action="legacy-minus">-1 Legacy</button><button type="button" data-action="legacy-plus">+1 Legacy</button><button type="button" data-action="perfected">Activate Perfected Art</button>${has(actor,'overwhelming-splinters')?'<button type="button" data-action="splinters">Overwhelming Splinters</button>':''}${level>=4?'<button type="button" data-action="suppression">Legacy Suppression</button>':''}${level>=2&&mut<needed?'<button type="button" data-action="mutation">Choose Mutation Skill</button>':''}${s.hostility?'<button type="button" data-action="hostility">Attempt Hostility Control</button>':''}<button type="button" data-action="restore">Restore Legacy Chakra</button></footer>${s.lastHostilityCheck?`<p class="hostility-log">Last Hostility check: ${esc(s.lastHostilityCheck)}</p>`:''}</div>`; }
function dialogKey(actor){return actorKey(actor);} function refreshDialog(actor){ const d=dialogs.get(dialogKey(actor)); if(d?.rendered)d.render({force:true}); }
async function openTracker(actor){ if(!getClassMod(actor))return ui.notifications.warn("No Hashirama Cells Class Mod found."); await ensureActor(actor); const key=dialogKey(actor); if(dialogs.get(key)?.rendered)return dialogs.get(key).bringToFront(); const d=new foundry.applications.api.DialogV2({window:{title:`Hashirama Cells — ${actor.name}`,icon:"fa-solid fa-tree",resizable:true},position:{width:650,height:"auto"},classes:["n5eb-hashirama-tracker-window"],content:trackerHtml(actor),buttons:[{action:"close",label:"Close"}]}); dialogs.set(key,d); d.addEventListener("render",()=>activateDialog(d,actor)); d.addEventListener("close",()=>dialogs.delete(key),{once:true}); await d.render({force:true}); return d; }
function activateDialog(dialog,actor){ const root=dialog.element?.querySelector?.('[data-hashirama-root]'); if(!root)return; const run=fn=>fn().catch(e=>{console.error(`${MODULE_ID} | Hashirama Cells automation failed`,e);ui.notifications.error(`Hashirama Cells automation failed: ${e.message}`);}); root.querySelector('[data-action="legacy-minus"]')?.addEventListener('click',()=>run(()=>changeLegacy(actor,-1))); root.querySelector('[data-action="legacy-plus"]')?.addEventListener('click',()=>run(()=>changeLegacy(actor,1))); root.querySelector('[data-action="perfected"]')?.addEventListener('click',()=>run(()=>activatePerfected(actor))); root.querySelector('[data-action="splinters"]')?.addEventListener('click',()=>run(()=>useSplinters(actor))); root.querySelector('[data-action="suppression"]')?.addEventListener('click',()=>run(()=>useLegacySuppression(actor))); root.querySelector('[data-action="mutation"]')?.addEventListener('click',()=>run(()=>chooseMutationSkill(actor))); root.querySelector('[data-action="hostility"]')?.addEventListener('click',()=>run(()=>hostilityCheck(actor,{escape:true}))); root.querySelector('[data-action="restore"]')?.addEventListener('click',()=>run(()=>writeTracker(actor,{legacy:maxLegacy(actor)}))); }
function renderRoot(app,html){return html?.[0]??html??app.element?.[0]??app.element;} function renderStrip(app,html){ const actor=app.actor??app.document;if(!getClassMod(actor))return;const root=renderRoot(app,html);if(!root||root.querySelector('[data-hashirama-strip]'))return;const target=root.querySelector('.jutsu-casting-overview')??root.querySelector('.sheet-body');if(!target)return;const s=readTracker(actor),section=document.createElement('section');section.className='n5eb-hashirama-tracker-strip';section.dataset.hashiramaStrip='true';section.innerHTML=`<button type="button" class="tracker-title" data-action="open-hashirama"><img src="${ICON}"> Hashirama Cells</button><div class="tracker-mini"><span>Legacy</span><strong>${s.legacy}/${maxLegacy(actor)}</strong></div><div class="tracker-mini"><span>Regen</span><strong>${esc(regenFormula(actor))}</strong></div><div class="tracker-mini"><span>Hostility</span><strong>${s.hostility?'ACTIVE':`DC ${s.hostilityDc}`}</strong></div>`;target.prepend(section);section.querySelector('[data-action="open-hashirama"]')?.addEventListener('click',()=>openTracker(actor)); }

Hooks.once("ready",async()=>{ if(game.system.id!=="n5eb")return; globalThis.N5eBHashiramaCells=Object.freeze({openTracker,getTracker:readTracker,spendLegacy,activatePerfected,useSplinters,useLegacySuppression,hostilityCheck}); if(game.user.isGM) for(const actor of game.actors??[]) if(getClassMod(actor)) await queue(actor,()=>ensureActor(actor)); });
Hooks.on("getActorSheetHeaderButtons",(sheet,buttons)=>{const actor=sheet.actor??sheet.document;if(!getClassMod(actor))return;const s=readTracker(actor);buttons.unshift({label:`Legacy ${s.legacy}/${maxLegacy(actor)}`,class:"n5eb-hashirama-tracker-button",icon:"fas fa-tree",onclick:()=>openTracker(actor)});});
Hooks.on("renderActorSheet",renderStrip); Hooks.on("renderCharacterActorSheet",renderStrip); Hooks.on("renderApplicationV2",renderStrip);
Hooks.on("createItem",async(item,options,userId)=>{if(options?.[INTERNAL]||userId!==game.user.id||item.parent?.documentName!=="Actor")return;const actor=item.parent;if((item.type==='classmod'&&item.system?.identifier===CLASSMOD_ID)||getClassMod(actor))await queue(actor,()=>ensureActor(actor));});
Hooks.on("updateItem",async(item,changes,options,userId)=>{if(options?.[INTERNAL]||userId!==game.user.id||item.parent?.documentName!=="Actor")return;const actor=item.parent;if(getClassMod(actor))await queue(actor,()=>ensureActor(actor));});
Hooks.on("deleteItem",async(item,options,userId)=>{if(options?.[INTERNAL]||userId!==game.user.id||item.parent?.documentName!=="Actor")return;const actor=item.parent;if(item.type==='classmod'&&item.system?.identifier===CLASSMOD_ID)await cleanupActor(actor);else if(getClassMod(actor))await queue(actor,()=>ensureActor(actor));});
Hooks.on("updateCombat",async(combat,changes,options,userId)=>{if(userId!==game.user.id||(!Object.hasOwn(changes,'turn')&&!Object.hasOwn(changes,'round')))return;const actor=combat.combatant?.actor;if(!actor||!getClassMod(actor))return;await queue(actor,()=>processTurn(actor,combat));});
Hooks.on("dnd5e.restCompleted",(actor,result)=>{if(getClassMod(actor))queue(actor,()=>applyRest(actor,result?.type)).catch(console.error);});
Hooks.on("dnd5e.preUseActivity",activity=>{const item=getActivityItem(activity),actor=activity?.actor??item?.actor;if(!actor||!getClassMod(actor)||!item)return;const state=readTracker(actor);if(state.hostility&&item.type==='spell'&&item.system?.jutsu){ui.notifications.warn(`${actor.name} cannot mold chakra during Wooden Hostility.`);return false;}});
Hooks.on("updateActor",async(actor,changes,options,userId)=>{if(options?.[INTERNAL]||userId!==game.user.id||!getClassMod(actor))return;const hp=foundry.utils.getProperty(changes,'system.attributes.hp.value');if(hp!==undefined&&Number(hp)/Math.max(1,Number(actor.system?.attributes?.hp?.max??1))>=.5&&readTracker(actor).hostilityDc!==20&&!readTracker(actor).hostility)await writeTracker(actor,{hostilityDc:20},{render:false,effects:false});refreshDialog(actor);});
