const MODULE_ID = "n5eb-classmod-library";
const CLASSMOD_ID = "madara-cells";
const TRACKER_FLAG = "madaraCellsTracker";
const EFFECT_FLAG = "madaraCellsPassiveEffect";
const HATRED_EFFECT_FLAG = "madaraCellsHatredEffect";
const INTERNAL = MODULE_ID;
const ICON = `modules/${MODULE_ID}/assets/madara-cells.png`;
const dialogs = new Map();
const queues = new Map();
const combatLastActor = new Map();

function arr(v){ return v ? (Array.isArray(v) ? v : Array.from(v)) : []; }
function esc(v){ return foundry.utils.escapeHTML(String(v ?? "")); }
function actorKey(actor){ return actor?.uuid ?? actor?.id ?? null; }
function queue(actor,task){ const key=actorKey(actor); if(!key)return Promise.resolve().then(task); const prior=queues.get(key)??Promise.resolve(); const current=prior.catch(()=>{}).then(task); queues.set(key,current); return current.finally(()=>{if(queues.get(key)===current)queues.delete(key);}); }
function flag(doc,key){ return doc?.getFlag?.(MODULE_ID,key) ?? doc?.flags?.[MODULE_ID]?.[key]; }
function getClassMod(actor){ return arr(actor?.items).find(i=>i.type==="classmod"&&i.system?.identifier===CLASSMOD_ID)??null; }
function getLevel(actor){ return Math.max(0,Math.min(5,Number(getClassMod(actor)?.system?.levels??0))); }
function has(actor,id){ return arr(actor?.items).some(i=>i.system?.identifier===id); }
function prof(actor){ return Math.max(0,Number(actor?.system?.attributes?.prof??0)); }
function conMod(actor){ const a=actor?.system?.abilities?.con??{}; return Number.isFinite(Number(a.mod))?Number(a.mod):Math.floor((Number(a.value??10)-10)/2); }
function maxLegacy(actor){ return 20*getLevel(actor); }
function maxDefence(actor){ return Math.max(0,Math.floor(prof(actor)/2)+getLevel(actor)); }
function clamp(v,min,max){ return Math.min(max,Math.max(min,Number(v)||0)); }
function currentTurnKey(combat=game.combat){ if(!combat)return ""; return `${combat.id}:${combat.round??0}:${combat.turn??0}`; }
function defaultTracker(actor){ return {version:1,legacy:maxLegacy(actor),defence:maxDefence(actor),defenceRoundKey:"",defenceUsedRound:0,defenceTurnKey:"",hatred:false,hatredDc:16,lastTurnKey:"",lastHatredCheck:"",zeroHatredTurns:0,lostToHatred:false,mutationSkills:{}}; }
function normalizeTracker(actor,v={}){ return {version:1,legacy:clamp(v.legacy,0,maxLegacy(actor)),defence:clamp(v.defence,0,maxDefence(actor)),defenceRoundKey:String(v.defenceRoundKey??""),defenceUsedRound:Math.max(0,Math.floor(Number(v.defenceUsedRound??0))),defenceTurnKey:String(v.defenceTurnKey??""),hatred:Boolean(v.hatred)&&getLevel(actor)<5,hatredDc:Math.max(16,Number(v.hatredDc??16)),lastTurnKey:String(v.lastTurnKey??""),lastHatredCheck:String(v.lastHatredCheck??""),zeroHatredTurns:Math.max(0,Math.floor(Number(v.zeroHatredTurns??0))),lostToHatred:Boolean(v.lostToHatred),mutationSkills:(v.mutationSkills&&typeof v.mutationSkills==="object")?v.mutationSkills:{}}; }
function readTracker(actor){ return normalizeTracker(actor,actor?.getFlag?.(MODULE_ID,TRACKER_FLAG)??defaultTracker(actor)); }
async function writeTracker(actor,patch={}, {render=true,effects=true}={}){ const next=normalizeTracker(actor,{...readTracker(actor),...patch}); const raw=actor?.getFlag?.(MODULE_ID,TRACKER_FLAG); if(!raw||JSON.stringify(raw)!==JSON.stringify(next)) await actor.update({[`flags.${MODULE_ID}.${TRACKER_FLAG}`]:next},{[INTERNAL]:{madara:true}}); if(effects)await refreshEffects(actor,next); if(render){actor.sheet?.render?.(false);refreshDialog(actor);} return next; }
function addChange(changes,key,value,mode=CONST.ACTIVE_EFFECT_MODES.ADD,priority=20){ if(Number(value))changes.push({key,mode,value:String(value),priority}); }
function skillAbility(skill){ return String(skill?.ability??skill?.abilityId??skill?.attribute??"").toLowerCase(); }
function passiveChanges(actor){ const level=getLevel(actor), changes=[]; if(!level)return changes;
  const dex=level>=5?4:2, intl=level>=5?4:level>=3?2:0; addChange(changes,"system.abilities.dex.value",dex); addChange(changes,"system.abilities.dex.max",dex); if(intl){addChange(changes,"system.abilities.int.value",intl);addChange(changes,"system.abilities.int.max",intl);}
  const move=level>=4?30:level>=2?15:0; addChange(changes,"system.attributes.movement.walk",move);
  if(level>=4){ for(const [key,s] of Object.entries(actor?.system?.skills??{})){ if(["dex","int","wis"].includes(skillAbility(s)))addChange(changes,`system.skills.${key}.bonuses.check`,level); } }
  if(has(actor,"movement-mastery"))addChange(changes,"system.attributes.movement.walk",10*level);
  if(has(actor,"madara-mental-mastery"))for(const a of ["int","wis","cha"])addChange(changes,`system.abilities.${a}.bonuses.save`,level);
  if(has(actor,"madara-physical-mastery"))for(const a of ["str","dex","con"])addChange(changes,`system.abilities.${a}.bonuses.save`,level);
  return changes;
}
async function refreshEffects(actor,state=readTracker(actor)){ let passive=arr(actor?.effects).find(e=>flag(e,EFFECT_FLAG)); if(!getClassMod(actor)){if(passive)await passive.delete({[INTERNAL]:{madara:true}});return;} const changes=passiveChanges(actor), data={name:"Madara Cells — Passive Adaptation",img:ICON,disabled:false,transfer:false,changes,statuses:[],flags:{[MODULE_ID]:{[EFFECT_FLAG]:true}}}; if(!passive)await actor.createEmbeddedDocuments("ActiveEffect",[data],{[INTERNAL]:{madara:true}}); else if(passive.img!==ICON||JSON.stringify(passive.changes??[])!==JSON.stringify(changes)||passive.disabled)await passive.update(data,{[INTERNAL]:{madara:true}});
  let hatred=arr(actor?.effects).find(e=>flag(e,HATRED_EFFECT_FLAG)); if(state.hatred&&getLevel(actor)<5){const h={name:"Overcome with Hatred",img:ICON,disabled:false,transfer:false,changes:[],statuses:[],flags:{[MODULE_ID]:{[HATRED_EFFECT_FLAG]:true}}};if(!hatred)await actor.createEmbeddedDocuments("ActiveEffect",[h],{[INTERNAL]:{madara:true}});else if(hatred.disabled||hatred.img!==ICON)await hatred.update(h,{[INTERNAL]:{madara:true}});}else if(hatred)await hatred.delete({[INTERNAL]:{madara:true}});
}
async function cleanupActor(actor){ const state=readTracker(actor), updates={}; for(const [key,data] of Object.entries(state.mutationSkills??{})){const path=data.kind==="tool"?`system.tools.${key}.value`:`system.skills.${key}.value`;const cur=Number(foundry.utils.getProperty(actor,path)??0);if(cur===Number(data.applied))updates[path]=Number(data.original??0);} if(Object.keys(updates).length)await actor.update(updates,{[INTERNAL]:{madara:true}}); const effects=arr(actor.effects).filter(e=>flag(e,EFFECT_FLAG)||flag(e,HATRED_EFFECT_FLAG));if(effects.length)await actor.deleteEmbeddedDocuments("ActiveEffect",effects.map(e=>e.id),{[INTERNAL]:{madara:true}});await actor.unsetFlag(MODULE_ID,TRACKER_FLAG);}
async function ensureActor(actor){if(!getClassMod(actor))return;const raw=actor.getFlag?.(MODULE_ID,TRACKER_FLAG);if(!raw)await writeTracker(actor,defaultTracker(actor),{render:false});else{const state=readTracker(actor);if(getLevel(actor)>=5&&state.hatred)await writeTracker(actor,{hatred:false,hatredDc:16,zeroHatredTurns:0},{render:false});else await refreshEffects(actor,state);}await ensureMutationChoices(actor);}
async function roll(actor,formula,label){const r=await new Roll(formula).evaluate();await r.toMessage({speaker:ChatMessage.getSpeaker({actor}),flavor:`${actor.name} — ${label}`});return Number(r.total??0);}
async function spendLegacy(actor,amount,reason="Legacy Chakra"){amount=Math.max(0,Math.floor(Number(amount)||0));if(!amount)return true;const s=readTracker(actor),fromLegacy=Math.min(s.legacy,amount),missing=amount-fromLegacy;let chakraCost=0;if(missing){if(getLevel(actor)<5){ui.notifications.warn(`Not enough Legacy Chakra (${s.legacy}/${amount}).`);return false;}chakraCost=missing*3;const chakra=Number(actor.system?.attributes?.chakra?.value??0);if(chakra<chakraCost){ui.notifications.warn(`Perfect Match needs ${chakraCost} regular Chakra for the missing ${missing} Legacy Chakra.`);return false;}await actor.update({"system.attributes.chakra.value":chakra-chakraCost},{[INTERNAL]:{madara:true}});}await writeTracker(actor,{legacy:s.legacy-fromLegacy},{render:false});ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>${esc(actor.name)} — ${esc(reason)}:</strong> spent ${amount} Legacy Chakra${chakraCost?` (${chakraCost} regular Chakra converted through Perfect Match)`:''}.</p>`});refreshDialog(actor);return true;}
async function changeLegacy(actor,delta){const s=readTracker(actor);await writeTracker(actor,{legacy:s.legacy+Number(delta||0)});}
function maxDefencePerRound(actor){const l=getLevel(actor);return l>=5?3:l>=3?2:1;}
async function spendDefence(actor){const s=readTracker(actor);if(s.defence<=0)return ui.notifications.warn("No Mastered Defence reactions remain.");const combat=game.combat,roundKey=combat?`${combat.id}:${combat.round??0}`:"",turnKey=currentTurnKey(combat);let used=s.defenceRoundKey===roundKey?s.defenceUsedRound:0;if(roundKey&&used>=maxDefencePerRound(actor))return ui.notifications.warn(`Mastered Defence is limited to ${maxDefencePerRound(actor)} additional reaction(s) per round at this Class Mod level.`);if(turnKey&&s.defenceTurnKey===turnKey)return ui.notifications.warn("Mastered Defence additional reactions can only be used once per turn.");await writeTracker(actor,{defence:s.defence-1,defenceRoundKey:roundKey,defenceUsedRound:used+1,defenceTurnKey:turnKey});ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>${esc(actor.name)}:</strong> spends 1 Mastered Defence reaction (${s.defence-1}/${maxDefence(actor)} remaining; ${used+1}/${maxDefencePerRound(actor)} this round).</p>`});}
async function refillDefence(actor){if(!await spendLegacy(actor,10,"Mastered Defence Refill"))return;await writeTracker(actor,{defence:maxDefence(actor),defenceRoundKey:"",defenceUsedRound:0,defenceTurnKey:""});}
async function activateMastered(actor){const arts=arr(actor.items).filter(i=>flag(i,"madaraMasteredTechnique"));if(!arts.length)return ui.notifications.warn("No Mastered Uchiha Technique is owned.");const opts=arts.map(i=>`<option value="${esc(i.id)}">${esc(i.name)}</option>`).join('');const id=await foundry.applications.api.DialogV2.wait({window:{title:"Mastered Uchiha Technique"},content:`<form><div class="form-group"><label for="mc-mastered-art">Technique</label><select id="mc-mastered-art" name="art">${opts}</select></div></form>`,buttons:[{action:"activate",label:"Spend 2 Legacy Chakra",default:true,callback:(e,b)=>new FormDataExtended(b.form).object.art},{action:"cancel",label:"Cancel"}],rejectClose:false});if(!id)return;const item=actor.items.get(id);if(!item||!await spendLegacy(actor,2,item.name))return;ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>${esc(item.name)}</strong> is empowered as a Mastered Technique for this casting.</p>${item.system?.description?.value??""}`});}
async function replenishSharingan(actor){const candidates=arr(actor.items).filter(i=>/sharingan/i.test(i.name??"")&&Number(i.system?.uses?.max??0)>0);if(!candidates.length)return ui.notifications.warn("No owned Sharingan item with a uses pool was found. The system item may store Sharingan uses elsewhere.");const opts=candidates.map(i=>`<option value="${esc(i.id)}">${esc(i.name)} (${Number(i.system?.uses?.value??0)}/${Number(i.system?.uses?.max??0)})</option>`).join('');const id=await foundry.applications.api.DialogV2.wait({window:{title:"Replenish Sharingan Use"},content:`<form><div class="form-group"><label for="mc-sharingan-item">Sharingan Feature</label><select id="mc-sharingan-item" name="item">${opts}</select></div></form>`,buttons:[{action:"restore",label:"Spend 1 Legacy Chakra",default:true,callback:(e,b)=>new FormDataExtended(b.form).object.item},{action:"cancel",label:"Cancel"}],rejectClose:false});if(!id)return;const item=actor.items.get(id);if(!item||!await spendLegacy(actor,1,"Sharingan Use"))return;const cur=Number(item.system?.uses?.value??0),max=Number(item.system?.uses?.max??cur);await item.update({"system.uses.value":Math.min(max,cur+1)},{[INTERNAL]:{madara:true}});}
async function convertMangekyo(actor){if(getLevel(actor)<5)return ui.notifications.warn("Perfect Match is required.");const candidates=arr(actor.items).filter(i=>/mangek/i.test(`${i.name??""} ${i.system?.identifier??""}`)&&Number(i.system?.uses?.max??0)>0);if(!candidates.length)return ui.notifications.warn("No Mangekyō item with a uses pool was found; no charge was changed.");const opts=candidates.map(i=>`<option value="${esc(i.id)}">${esc(i.name)} (${Number(i.system?.uses?.value??0)}/${Number(i.system?.uses?.max??0)})</option>`).join('');const res=await foundry.applications.api.DialogV2.wait({window:{title:"Mangekyō Synergy"},content:`<form><div class="form-group"><label for="mc-mangekyo-item">Mangekyō Feature</label><select id="mc-mangekyo-item" name="item">${opts}</select></div><div class="form-group"><label for="mc-mangekyo-count">Charges</label><input id="mc-mangekyo-count" name="count" type="number" min="1" value="1"></div></form>`,buttons:[{action:"convert",label:"Convert Legacy Chakra",default:true,callback:(e,b)=>new FormDataExtended(b.form).object},{action:"cancel",label:"Cancel"}],rejectClose:false});if(!res)return;const item=actor.items.get(res.item),count=Math.max(1,Math.floor(Number(res.count)||1));if(!item||!await spendLegacy(actor,10*count,"Mangekyō Art Charges"))return;const cur=Number(item.system?.uses?.value??0),max=Number(item.system?.uses?.max??cur+count);await item.update({"system.uses.value":Math.min(max,cur+count)},{[INTERNAL]:{madara:true}});}
function requiredMutationCount(actor){const l=getLevel(actor);return l<2?0:l-1;}
async function ensureMutationChoices(actor){const need=requiredMutationCount(actor),have=Object.keys(readTracker(actor).mutationSkills??{}).length;if(need>have&&actor.isOwner)ui.notifications.info(`${actor.name} can choose ${need-have} Madara Cells mutation proficiency${need-have===1?'':'ies'} from the tracker.`);}
async function chooseMutation(actor){const s=readTracker(actor),chosen=s.mutationSkills??{},need=requiredMutationCount(actor);if(Object.keys(chosen).length>=need)return ui.notifications.info("All current Extraordinary Talent choices are already assigned.");const options=[];for(const [key,v] of Object.entries(actor.system?.skills??{}))if(!chosen[`skill:${key}`])options.push({id:`skill:${key}`,label:v.label??CONFIG.DND5E?.skills?.[key]?.label??key,value:Number(v.value??0),kind:'skill',key});for(const [key,v] of Object.entries(actor.system?.tools??{}))if(!chosen[`tool:${key}`])options.push({id:`tool:${key}`,label:v.label??key,value:Number(v.value??0),kind:'tool',key});if(!options.length)return ui.notifications.warn("No eligible skill/tool entries were found.");options.sort((a,b)=>a.label.localeCompare(b.label));const html=options.map(o=>`<option value="${esc(o.id)}">${esc(o.label)} — ${o.value>0?'increase Mastery':'gain Proficiency'}</option>`).join('');const id=await foundry.applications.api.DialogV2.wait({window:{title:"Extraordinary Talent"},content:`<form><div class="form-group"><label for="mc-mutation-choice">Skill or Tool</label><select id="mc-mutation-choice" name="choice">${html}</select></div></form>`,buttons:[{action:"apply",label:"Apply",default:true,callback:(e,b)=>new FormDataExtended(b.form).object.choice},{action:"cancel",label:"Cancel"}],rejectClose:false});const o=options.find(x=>x.id===id);if(!o)return;const path=o.kind==='tool'?`system.tools.${o.key}.value`:`system.skills.${o.key}.value`,original=Number(foundry.utils.getProperty(actor,path)??0),applied=original>0?original+1:1;await actor.update({[path]:applied},{[INTERNAL]:{madara:true}});await writeTracker(actor,{mutationSkills:{...chosen,[id]:{kind:o.kind,key:o.key,original,applied}}});}
async function hatredCheck(actor,{escape=false}={}){if(getLevel(actor)>=5)return true;const s=readTracker(actor),adv=has(actor,"madara-partial-match"),formula=`${adv?'2d20kh':'1d20'}${conMod(actor)>=0?'+':''}${conMod(actor)}`,total=await roll(actor,formula,escape?"Overcome with Hatred — Control Check":"Madara Cells — Hatred Surge");const success=total>=s.hatredDc;if(success){await writeTracker(actor,{hatred:escape?false:s.hatred,hatredDc:escape?s.hatredDc:s.hatredDc+1,lastHatredCheck:`${total} vs DC ${s.hatredDc} — success`,zeroHatredTurns:escape?0:s.zeroHatredTurns},{render:false});}else{await writeTracker(actor,{hatred:true,lastHatredCheck:`${total} vs DC ${s.hatredDc} — failure`},{render:false});ui.notifications.warn(`${actor.name} is Overcome with Hatred.`);}refreshDialog(actor);return success;}
async function hatredAttackReminder(actor){ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>${esc(actor.name)} is Overcome with Hatred.</strong> Per Hatred Surge, the DM secretly determines a random nearby person and ${esc(actor.name)} attacks that target as aggressively and quickly as possible.</p>`});}
async function processTurnStart(actor,combat){const level=getLevel(actor);if(!level)return;const key=currentTurnKey(combat),s=readTracker(actor);if(!key||s.lastTurnKey===key)return;await writeTracker(actor,{lastTurnKey:key},{render:false,effects:false});if(level>=5){if(s.hatred)await writeTracker(actor,{hatred:false,hatredDc:16,zeroHatredTurns:0},{render:false});return;}const hp=actor.system?.attributes?.hp??{},value=Number(hp.value??0),max=Math.max(1,Number(hp.max??1));const state=readTracker(actor);if(state.hatred){await hatredAttackReminder(actor);if(value<=0){const turns=state.zeroHatredTurns+1;if(turns>=3){await actor.update({"system.attributes.hp.value":1},{[INTERNAL]:{madara:true}});await writeTracker(actor,{zeroHatredTurns:3,lostToHatred:true},{render:false});ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>${esc(actor.name)}:</strong> after 3 turns at 0 HP while Overcome with Hatred, the cells take over. HP is set to 1; per the Class Mod this character now flees and becomes an NPC under the DM's control.</p>`});}else await writeTracker(actor,{zeroHatredTurns:turns},{render:false});}return;}if(value/max<.25){const ok=await hatredCheck(actor);if(!ok)await hatredAttackReminder(actor);}}
async function processTurnEnd(actor){if(!getClassMod(actor)||getLevel(actor)>=5)return;const s=readTracker(actor);if(s.hatred)await hatredCheck(actor,{escape:true});}
async function applyRest(actor,type){if(!["long","full"].includes(type))return;await writeTracker(actor,{legacy:maxLegacy(actor),defence:maxDefence(actor),defenceRoundKey:"",defenceUsedRound:0,defenceTurnKey:"",hatredDc:16,lastTurnKey:"",zeroHatredTurns:0},{render:false});ChatMessage.create({speaker:ChatMessage.getSpeaker({actor}),content:`<p><strong>${esc(actor.name)} — Madara Cells:</strong> Legacy Chakra restored to ${maxLegacy(actor)} and Mastered Defence restored to ${maxDefence(actor)}.</p>`});refreshDialog(actor);}
function sharinganStatus(actor){const l=getLevel(actor);if(l<2)return'—';return l>=4?'Additional 1/2/3-Tomoe features':'Additional 1/2-Tomoe features';}
function trackerHtml(actor){const s=readTracker(actor),l=getLevel(actor),m=Object.keys(s.mutationSkills??{}).length,need=requiredMutationCount(actor),mastered=arr(actor.items).filter(i=>flag(i,'madaraMasteredTechnique')).length;return `<div class="n5eb-madara-tracker" data-madara-root><header><div><h2>Madara Cells</h2><p>Class Mod Level ${l}</p></div><div class="legacy-orb">${s.legacy}<small>/${maxLegacy(actor)}</small></div></header><section class="madara-grid"><div><span>Legacy Chakra</span><strong>${s.legacy}/${maxLegacy(actor)}</strong></div><div><span>Mastered Defence</span><strong>${s.defence}/${maxDefence(actor)}</strong></div><div><span>Hatred Surge</span><strong>${l>=5?'REMOVED':s.hatred?'ACTIVE':`DC ${s.hatredDc}`}</strong></div><div><span>Mastered Techniques</span><strong>${mastered}/${l+1}</strong></div><div><span>Mutation Choices</span><strong>${m}/${need}</strong></div><div><span>Partial Match</span><strong>${esc(sharinganStatus(actor))}</strong></div></section><footer><button type="button" data-action="legacy-minus">-1 Legacy</button><button type="button" data-action="legacy-plus">+1 Legacy</button><button type="button" data-action="mastered">Activate Mastered Technique</button><button type="button" data-action="defence">Spend Defence Reaction</button><button type="button" data-action="refill-defence">Refill Defence (10 Legacy)</button><button type="button" data-action="sharingan">Replenish Sharingan Use</button>${l>=2&&m<need?'<button type="button" data-action="mutation">Choose Mutation</button>':''}${s.hatred?'<button type="button" data-action="hatred">Attempt Hatred Control</button>':''}${l>=5?'<button type="button" data-action="mangekyo">Legacy → Mangekyō Charge</button>':''}<button type="button" data-action="restore">Restore Pools</button></footer>${s.lastHatredCheck?`<p class="hostility-log">Last Hatred check: ${esc(s.lastHatredCheck)}</p>`:''}${s.lostToHatred?'<p class="hostility-log"><strong>Cells have taken over this character per Hatred Surge.</strong></p>':''}</div>`;}
function dialogKey(actor){return actorKey(actor);}function refreshDialog(actor){const d=dialogs.get(dialogKey(actor));if(d?.rendered)d.render({force:true});}
async function openTracker(actor){if(!getClassMod(actor))return ui.notifications.warn("No Madara Cells Class Mod found.");await ensureActor(actor);const key=dialogKey(actor);if(dialogs.get(key)?.rendered)return dialogs.get(key).bringToFront();const d=new foundry.applications.api.DialogV2({window:{title:`Madara Cells — ${actor.name}`,icon:"fa-solid fa-eye",resizable:true},position:{width:680,height:"auto"},classes:["n5eb-madara-tracker-window"],content:trackerHtml(actor),buttons:[{action:"close",label:"Close"}]});dialogs.set(key,d);d.addEventListener("render",()=>activateDialog(d,actor));d.addEventListener("close",()=>dialogs.delete(key),{once:true});await d.render({force:true});return d;}
function activateDialog(dialog,actor){const root=dialog.element?.querySelector?.('[data-madara-root]');if(!root)return;const run=fn=>fn().catch(e=>{console.error(`${MODULE_ID} | Madara Cells automation failed`,e);ui.notifications.error(`Madara Cells automation failed: ${e.message}`);});root.querySelector('[data-action="legacy-minus"]')?.addEventListener('click',()=>run(()=>changeLegacy(actor,-1)));root.querySelector('[data-action="legacy-plus"]')?.addEventListener('click',()=>run(()=>changeLegacy(actor,1)));root.querySelector('[data-action="mastered"]')?.addEventListener('click',()=>run(()=>activateMastered(actor)));root.querySelector('[data-action="defence"]')?.addEventListener('click',()=>run(()=>spendDefence(actor)));root.querySelector('[data-action="refill-defence"]')?.addEventListener('click',()=>run(()=>refillDefence(actor)));root.querySelector('[data-action="sharingan"]')?.addEventListener('click',()=>run(()=>replenishSharingan(actor)));root.querySelector('[data-action="mutation"]')?.addEventListener('click',()=>run(()=>chooseMutation(actor)));root.querySelector('[data-action="hatred"]')?.addEventListener('click',()=>run(()=>hatredCheck(actor,{escape:true})));root.querySelector('[data-action="mangekyo"]')?.addEventListener('click',()=>run(()=>convertMangekyo(actor)));root.querySelector('[data-action="restore"]')?.addEventListener('click',()=>run(()=>writeTracker(actor,{legacy:maxLegacy(actor),defence:maxDefence(actor),defenceRoundKey:"",defenceUsedRound:0,defenceTurnKey:""})));}
function renderRoot(app,html){return html?.[0]??html??app.element?.[0]??app.element;}function renderStrip(app,html){const actor=app.actor??app.document;if(!getClassMod(actor))return;const root=renderRoot(app,html);if(!root||root.querySelector('[data-madara-strip]'))return;const target=root.querySelector('.jutsu-casting-overview')??root.querySelector('.sheet-body');if(!target)return;const s=readTracker(actor),section=document.createElement('section');section.className='n5eb-madara-tracker-strip';section.dataset.madaraStrip='true';section.innerHTML=`<button type="button" class="tracker-title" data-action="open-madara"><img src="${ICON}"> Madara Cells</button><div class="tracker-mini"><span>Legacy</span><strong>${s.legacy}/${maxLegacy(actor)}</strong></div><div class="tracker-mini"><span>Defence</span><strong>${s.defence}/${maxDefence(actor)}</strong></div><div class="tracker-mini"><span>Hatred</span><strong>${getLevel(actor)>=5?'REMOVED':s.hatred?'ACTIVE':`DC ${s.hatredDc}`}</strong></div>`;target.prepend(section);section.querySelector('[data-action="open-madara"]')?.addEventListener('click',()=>openTracker(actor));}
Hooks.once("ready",async()=>{if(game.system.id!=="n5eb")return;globalThis.N5eBMadaraCells=Object.freeze({openTracker,getTracker:readTracker,spendLegacy,spendDefence,activateMastered,hatredCheck,replenishSharingan,convertMangekyo});if(game.user.isGM)for(const actor of game.actors??[])if(getClassMod(actor))await queue(actor,()=>ensureActor(actor));});
Hooks.on("getActorSheetHeaderButtons",(sheet,buttons)=>{const actor=sheet.actor??sheet.document;if(!getClassMod(actor))return;const s=readTracker(actor);buttons.unshift({label:`Legacy ${s.legacy}/${maxLegacy(actor)} · MD ${s.defence}/${maxDefence(actor)}`,class:"n5eb-madara-tracker-button",icon:"fas fa-eye",onclick:()=>openTracker(actor)});});
Hooks.on("renderActorSheet",renderStrip);Hooks.on("renderCharacterActorSheet",renderStrip);Hooks.on("renderApplicationV2",renderStrip);
Hooks.on("createItem",async(item,options,userId)=>{if(options?.[INTERNAL]||userId!==game.user.id||item.parent?.documentName!=="Actor")return;const actor=item.parent;if((item.type==='classmod'&&item.system?.identifier===CLASSMOD_ID)||getClassMod(actor))await queue(actor,()=>ensureActor(actor));});
Hooks.on("updateItem",async(item,changes,options,userId)=>{if(options?.[INTERNAL]||userId!==game.user.id||item.parent?.documentName!=="Actor")return;const actor=item.parent;if(getClassMod(actor))await queue(actor,()=>ensureActor(actor));});
Hooks.on("deleteItem",async(item,options,userId)=>{if(options?.[INTERNAL]||userId!==game.user.id||item.parent?.documentName!=="Actor")return;const actor=item.parent;if(item.type==='classmod'&&item.system?.identifier===CLASSMOD_ID)await cleanupActor(actor);else if(getClassMod(actor))await queue(actor,()=>ensureActor(actor));});
Hooks.on("updateCombat",async(combat,changes,options,userId)=>{if(!game.user.isGM||(!Object.hasOwn(changes,'turn')&&!Object.hasOwn(changes,'round')))return;const prevId=combatLastActor.get(combat.id);const current=combat.combatant?.actor;if(prevId&&prevId!==current?.id){const prev=game.actors.get(prevId);if(prev&&getClassMod(prev))await queue(prev,()=>processTurnEnd(prev));}if(current){combatLastActor.set(combat.id,current.id);if(getClassMod(current))await queue(current,()=>processTurnStart(current,combat));}});
Hooks.on("deleteCombat",combat=>combatLastActor.delete(combat.id));
Hooks.on("dnd5e.restCompleted",(actor,result)=>{if(getClassMod(actor))queue(actor,()=>applyRest(actor,result?.type)).catch(console.error);});
Hooks.on("updateActor",async(actor,changes,options,userId)=>{if(options?.[INTERNAL]||userId!==game.user.id||!getClassMod(actor))return;const hp=foundry.utils.getProperty(changes,'system.attributes.hp.value');if(hp!==undefined){const max=Math.max(1,Number(actor.system?.attributes?.hp?.max??1));if(Number(hp)/max>=.25&&!readTracker(actor).hatred&&readTracker(actor).hatredDc!==16)await writeTracker(actor,{hatredDc:16,zeroHatredTurns:0},{render:false,effects:false});}refreshDialog(actor);});
